runmode: debug             # 开发模式, debug, release, test
addr: :6666                 # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:6666   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数尝试的次数...
log:
  writers: file,stdout # 输出格式,file表示输出到文件,stdout表示标准输出,可同时使用
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: true # false 表示以JSON格式输出
  rollingPolicy: size # 可选的有 daily 和 size。如果选 daily 则根据天进行转存，如果是 size 则根据大小进行转存
  log_rotate_date: 1 #单位为天配合rollingPolicy:daily使用
  log_rotate_size: 1 # 单位为MB配合rollingPolicy: size使用
  log_backup_count: 7 # 日志备份保存的份数
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: cat
  password: catpass